/**
 * Component Registry - AUTOMATICALLY GENERATED
 *
 * This file is auto-generated by the build-registry.ts script.
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Total components registered: 86
 */
import React from "react"

interface ComponentEntry {
  source: string
  type: "example" | "chart" | "block"
  // eslint-disable-next-line
  component: React.LazyExoticComponent<any>
}

const COMPONENT_REGISTRY: Record<string, ComponentEntry> = {
  "textarea-example": {
    type: "example",
    source: "./examples/textarea/textarea-example.tsx",
    component: React.lazy(() => import("@/examples/textarea/textarea-example")),
  },

  "theme-toggler": {
    type: "example",
    source: "./examples/theme/theme-toggler.tsx",
    component: React.lazy(() => import("@/examples/theme/theme-toggler")),
  },

  "tabs-example": {
    type: "example",
    source: "./examples/tabs/tabs-example.tsx",
    component: React.lazy(() => import("@/examples/tabs/tabs-example")),
  },

  "table-example": {
    type: "example",
    source: "./examples/table/table-example.tsx",
    component: React.lazy(() => import("@/examples/table/table-example")),
  },

  "switch-example": {
    type: "example",
    source: "./examples/switch/switch-example.tsx",
    component: React.lazy(() => import("@/examples/switch/switch-example")),
  },

  "skeleton-example": {
    type: "example",
    source: "./examples/skeleton/skeleton-example.tsx",
    component: React.lazy(() => import("@/examples/skeleton/skeleton-example")),
  },
  "skeleton-card": {
    type: "example",
    source: "./examples/skeleton/skeleton-card.tsx",
    component: React.lazy(() => import("@/examples/skeleton/skeleton-card")),
  },

  "separator-example": {
    type: "example",
    source: "./examples/separator/separator-example.tsx",
    component: React.lazy(
      () => import("@/examples/separator/separator-example"),
    ),
  },

  "select-scrollable": {
    type: "example",
    source: "./examples/select/select-scrollable.tsx",
    component: React.lazy(() => import("@/examples/select/select-scrollable")),
  },
  "select-example": {
    type: "example",
    source: "./examples/select/select-example.tsx",
    component: React.lazy(() => import("@/examples/select/select-example")),
  },

  "scroll-area-horizontal": {
    type: "example",
    source: "./examples/scroll-area/scroll-area-horizontal.tsx",
    component: React.lazy(
      () => import("@/examples/scroll-area/scroll-area-horizontal"),
    ),
  },
  "scroll-area-example": {
    type: "example",
    source: "./examples/scroll-area/scroll-area-example.tsx",
    component: React.lazy(
      () => import("@/examples/scroll-area/scroll-area-example"),
    ),
  },

  "radio-group-example": {
    type: "example",
    source: "./examples/radio-group/radio-group-example.tsx",
    component: React.lazy(
      () => import("@/examples/radio-group/radio-group-example"),
    ),
  },

  "progress-example": {
    type: "example",
    source: "./examples/progress/progress-example.tsx",
    component: React.lazy(() => import("@/examples/progress/progress-example")),
  },

  "popover-example": {
    type: "example",
    source: "./examples/popover/popover-example.tsx",
    component: React.lazy(() => import("@/examples/popover/popover-example")),
  },

  "pagination-example": {
    type: "example",
    source: "./examples/pagination/pagination-example.tsx",
    component: React.lazy(
      () => import("@/examples/pagination/pagination-example"),
    ),
  },

  "input-with-icon": {
    type: "example",
    source: "./examples/input/input-with-icon.tsx",
    component: React.lazy(() => import("@/examples/input/input-with-icon")),
  },
  "input-variants": {
    type: "example",
    source: "./examples/input/input-variants.tsx",
    component: React.lazy(() => import("@/examples/input/input-variants")),
  },
  "input-floating-label": {
    type: "example",
    source: "./examples/input/input-floating-label.tsx",
    component: React.lazy(
      () => import("@/examples/input/input-floating-label"),
    ),
  },
  "input-floating-label-icon": {
    type: "example",
    source: "./examples/input/input-floating-label-icon.tsx",
    component: React.lazy(
      () => import("@/examples/input/input-floating-label-icon"),
    ),
  },
  "input-example": {
    type: "example",
    source: "./examples/input/input-example.tsx",
    component: React.lazy(() => import("@/examples/input/input-example")),
  },

  "label-example": {
    type: "example",
    source: "./examples/label/label-example.tsx",
    component: React.lazy(() => import("@/examples/label/label-example")),
  },

  "dropdown-menu-radio-group": {
    type: "example",
    source: "./examples/dropdown-menu/dropdown-menu-radio-group.tsx",
    component: React.lazy(
      () => import("@/examples/dropdown-menu/dropdown-menu-radio-group"),
    ),
  },
  "dropdown-menu-example": {
    type: "example",
    source: "./examples/dropdown-menu/dropdown-menu-example.tsx",
    component: React.lazy(
      () => import("@/examples/dropdown-menu/dropdown-menu-example"),
    ),
  },
  "dropdown-menu-checkboxes": {
    type: "example",
    source: "./examples/dropdown-menu/dropdown-menu-checkboxes.tsx",
    component: React.lazy(
      () => import("@/examples/dropdown-menu/dropdown-menu-checkboxes"),
    ),
  },

  "dialog-example": {
    type: "example",
    source: "./examples/dialog/dialog-example.tsx",
    component: React.lazy(() => import("@/examples/dialog/dialog-example")),
  },

  "date-picker-example": {
    type: "example",
    source: "./examples/date-picker/date-picker-example.tsx",
    component: React.lazy(
      () => import("@/examples/date-picker/date-picker-example"),
    ),
  },

  "checkbox-sizes": {
    type: "example",
    source: "./examples/checkbox/checkbox-sizes.tsx",
    component: React.lazy(() => import("@/examples/checkbox/checkbox-sizes")),
  },
  "checkbox-example": {
    type: "example",
    source: "./examples/checkbox/checkbox-example.tsx",
    component: React.lazy(() => import("@/examples/checkbox/checkbox-example")),
  },
  "checkbox-colors": {
    type: "example",
    source: "./examples/checkbox/checkbox-colors.tsx",
    component: React.lazy(() => import("@/examples/checkbox/checkbox-colors")),
  },

  "command-example": {
    type: "example",
    source: "./examples/command/command-example.tsx",
    component: React.lazy(() => import("@/examples/command/command-example")),
  },
  "command-dialog": {
    type: "example",
    source: "./examples/command/command-dialog.tsx",
    component: React.lazy(() => import("@/examples/command/command-dialog")),
  },

  "card-stats": {
    type: "example",
    source: "./examples/card/card-stats.tsx",
    component: React.lazy(() => import("@/examples/card/card-stats")),
  },
  "card-example": {
    type: "example",
    source: "./examples/card/card-example.tsx",
    component: React.lazy(() => import("@/examples/card/card-example")),
  },

  "calendar-example": {
    type: "example",
    source: "./examples/calendar/calendar-example.tsx",
    component: React.lazy(() => import("@/examples/calendar/calendar-example")),
  },

  "button-subtle": {
    type: "example",
    source: "./examples/button/button-subtle.tsx",
    component: React.lazy(() => import("@/examples/button/button-subtle")),
  },
  "button-sizes": {
    type: "example",
    source: "./examples/button/button-sizes.tsx",
    component: React.lazy(() => import("@/examples/button/button-sizes")),
  },
  "button-radius": {
    type: "example",
    source: "./examples/button/button-radius.tsx",
    component: React.lazy(() => import("@/examples/button/button-radius")),
  },
  "button-outlined": {
    type: "example",
    source: "./examples/button/button-outlined.tsx",
    component: React.lazy(() => import("@/examples/button/button-outlined")),
  },
  "button-icon-only": {
    type: "example",
    source: "./examples/button/button-icon-only.tsx",
    component: React.lazy(() => import("@/examples/button/button-icon-only")),
  },
  "button-ghost": {
    type: "example",
    source: "./examples/button/button-ghost.tsx",
    component: React.lazy(() => import("@/examples/button/button-ghost")),
  },
  "button-filled": {
    type: "example",
    source: "./examples/button/button-filled.tsx",
    component: React.lazy(() => import("@/examples/button/button-filled")),
  },
  "button-example": {
    type: "example",
    source: "./examples/button/button-example.tsx",
    component: React.lazy(() => import("@/examples/button/button-example")),
  },
  "button-colors": {
    type: "example",
    source: "./examples/button/button-colors.tsx",
    component: React.lazy(() => import("@/examples/button/button-colors")),
  },

  "badge-subtle": {
    type: "example",
    source: "./examples/badge/badge-subtle.tsx",
    component: React.lazy(() => import("@/examples/badge/badge-subtle")),
  },
  "badge-sizes": {
    type: "example",
    source: "./examples/badge/badge-sizes.tsx",
    component: React.lazy(() => import("@/examples/badge/badge-sizes")),
  },
  "badge-radius": {
    type: "example",
    source: "./examples/badge/badge-radius.tsx",
    component: React.lazy(() => import("@/examples/badge/badge-radius")),
  },
  "badge-override": {
    type: "example",
    source: "./examples/badge/badge-override.tsx",
    component: React.lazy(() => import("@/examples/badge/badge-override")),
  },
  "badge-outlined": {
    type: "example",
    source: "./examples/badge/badge-outlined.tsx",
    component: React.lazy(() => import("@/examples/badge/badge-outlined")),
  },
  "badge-ghost": {
    type: "example",
    source: "./examples/badge/badge-ghost.tsx",
    component: React.lazy(() => import("@/examples/badge/badge-ghost")),
  },
  "badge-filled": {
    type: "example",
    source: "./examples/badge/badge-filled.tsx",
    component: React.lazy(() => import("@/examples/badge/badge-filled")),
  },
  "badge-example": {
    type: "example",
    source: "./examples/badge/badge-example.tsx",
    component: React.lazy(() => import("@/examples/badge/badge-example")),
  },
  "badge-colors": {
    type: "example",
    source: "./examples/badge/badge-colors.tsx",
    component: React.lazy(() => import("@/examples/badge/badge-colors")),
  },

  "avatar-sizes": {
    type: "example",
    source: "./examples/avatar/avatar-sizes.tsx",
    component: React.lazy(() => import("@/examples/avatar/avatar-sizes")),
  },
  "avatar-group": {
    type: "example",
    source: "./examples/avatar/avatar-group.tsx",
    component: React.lazy(() => import("@/examples/avatar/avatar-group")),
  },
  "avatar-example": {
    type: "example",
    source: "./examples/avatar/avatar-example.tsx",
    component: React.lazy(() => import("@/examples/avatar/avatar-example")),
  },

  "autocomplete-example": {
    type: "example",
    source: "./examples/autocomplete/autocomplete-example.tsx",
    component: React.lazy(
      () => import("@/examples/autocomplete/autocomplete-example"),
    ),
  },
  "autocomplete-example-3": {
    type: "example",
    source: "./examples/autocomplete/autocomplete-example-3.tsx",
    component: React.lazy(
      () => import("@/examples/autocomplete/autocomplete-example-3"),
    ),
  },
  "autocomplete-example-2": {
    type: "example",
    source: "./examples/autocomplete/autocomplete-example-2.tsx",
    component: React.lazy(
      () => import("@/examples/autocomplete/autocomplete-example-2"),
    ),
  },

  "alert-dialog-example": {
    type: "example",
    source: "./examples/alert-dialog/alert-dialog-example.tsx",
    component: React.lazy(
      () => import("@/examples/alert-dialog/alert-dialog-example"),
    ),
  },

  "alert-outlined": {
    type: "example",
    source: "./examples/alert/alert-outlined.tsx",
    component: React.lazy(() => import("@/examples/alert/alert-outlined")),
  },
  "alert-filled": {
    type: "example",
    source: "./examples/alert/alert-filled.tsx",
    component: React.lazy(() => import("@/examples/alert/alert-filled")),
  },
  "alert-example": {
    type: "example",
    source: "./examples/alert/alert-example.tsx",
    component: React.lazy(() => import("@/examples/alert/alert-example")),
  },
  "alert-colors": {
    type: "example",
    source: "./examples/alert/alert-colors.tsx",
    component: React.lazy(() => import("@/examples/alert/alert-colors")),
  },

  "accordion-unstyled": {
    type: "example",
    source: "./examples/accordion/accordion-unstyled.tsx",
    component: React.lazy(
      () => import("@/examples/accordion/accordion-unstyled"),
    ),
  },
  "accordion-single": {
    type: "example",
    source: "./examples/accordion/accordion-single.tsx",
    component: React.lazy(
      () => import("@/examples/accordion/accordion-single"),
    ),
  },
  "accordion-outlined": {
    type: "example",
    source: "./examples/accordion/accordion-outlined.tsx",
    component: React.lazy(
      () => import("@/examples/accordion/accordion-outlined"),
    ),
  },
  "accordion-multiple": {
    type: "example",
    source: "./examples/accordion/accordion-multiple.tsx",
    component: React.lazy(
      () => import("@/examples/accordion/accordion-multiple"),
    ),
  },
  "accordion-filled": {
    type: "example",
    source: "./examples/accordion/accordion-filled.tsx",
    component: React.lazy(
      () => import("@/examples/accordion/accordion-filled"),
    ),
  },
  "accordion-custom-styles": {
    type: "example",
    source: "./examples/accordion/accordion-custom-styles.tsx",
    component: React.lazy(
      () => import("@/examples/accordion/accordion-custom-styles"),
    ),
  },
  "accordion-custom-icon": {
    type: "example",
    source: "./examples/accordion/accordion-custom-icon.tsx",
    component: React.lazy(
      () => import("@/examples/accordion/accordion-custom-icon"),
    ),
  },

  "line-chart-06": {
    type: "chart",
    source: "./charts/line-chart-06.tsx",
    component: React.lazy(() => import("@/charts/line-chart-06")),
  },
  "line-chart-05": {
    type: "chart",
    source: "./charts/line-chart-05.tsx",
    component: React.lazy(() => import("@/charts/line-chart-05")),
  },
  "line-chart-04": {
    type: "chart",
    source: "./charts/line-chart-04.tsx",
    component: React.lazy(() => import("@/charts/line-chart-04")),
  },
  "line-chart-03": {
    type: "chart",
    source: "./charts/line-chart-03.tsx",
    component: React.lazy(() => import("@/charts/line-chart-03")),
  },
  "line-chart-02": {
    type: "chart",
    source: "./charts/line-chart-02.tsx",
    component: React.lazy(() => import("@/charts/line-chart-02")),
  },
  "line-chart-01": {
    type: "chart",
    source: "./charts/line-chart-01.tsx",
    component: React.lazy(() => import("@/charts/line-chart-01")),
  },
  "bar-chart-05": {
    type: "chart",
    source: "./charts/bar-chart-05.tsx",
    component: React.lazy(() => import("@/charts/bar-chart-05")),
  },
  "bar-chart-04": {
    type: "chart",
    source: "./charts/bar-chart-04.tsx",
    component: React.lazy(() => import("@/charts/bar-chart-04")),
  },
  "bar-chart-03": {
    type: "chart",
    source: "./charts/bar-chart-03.tsx",
    component: React.lazy(() => import("@/charts/bar-chart-03")),
  },
  "bar-chart-02": {
    type: "chart",
    source: "./charts/bar-chart-02.tsx",
    component: React.lazy(() => import("@/charts/bar-chart-02")),
  },
  "bar-chart-01": {
    type: "chart",
    source: "./charts/bar-chart-01.tsx",
    component: React.lazy(() => import("@/charts/bar-chart-01")),
  },
  "area-chart-04": {
    type: "chart",
    source: "./charts/area-chart-04.tsx",
    component: React.lazy(() => import("@/charts/area-chart-04")),
  },
  "area-chart-03": {
    type: "chart",
    source: "./charts/area-chart-03.tsx",
    component: React.lazy(() => import("@/charts/area-chart-03")),
  },
  "area-chart-02": {
    type: "chart",
    source: "./charts/area-chart-02.tsx",
    component: React.lazy(() => import("@/charts/area-chart-02")),
  },
  "area-chart-01": {
    type: "chart",
    source: "./charts/area-chart-01.tsx",
    component: React.lazy(() => import("@/charts/area-chart-01")),
  },
}

export default COMPONENT_REGISTRY
